export const tagTypes = {
    favourite: 'favourite',
    prescription: 'prescription',
    patient: 'patient',
    appointments: 'appointments',
    doctor: 'doctor',
    reviews: 'reviews',
    timeSlot: 'timeSlot',
    blogs: 'blogs',
    service: 'service',
    chart: 'chart',
    location: 'location',
    license: 'license',
    profile: 'profile',
    password: 'password',
    avarar: 'avatar',
}

export const tagTypeList = [
    tagTypes.favourite,
    tagTypes.prescription,
    tagTypes.patient,
    tagTypes.appointments,
    tagTypes.doctor,
    tagTypes.reviews,
    tagTypes.timeSlot,
    tagTypes.blogs,
    tagTypes.service,
    tagTypes.chart,
    tagTypes.location,
    tagTypes.license,
    tagTypes.profile,
    tagTypes.password,
    tagTypes.avatar,
]
